### ISSUE TITLE
Protected vs Private

### ISSUE THREAD

**Issue by DarkMukke** [wellcometrust/dotmailer-php#16] opened 2018-11-08 16:53 UTC
I do not understand why your members are all private, it kills extend-ability.
Could we not change them so I can at least add my own functionality ?
Right now I have to fork it, add it to my own packagist and change my composer to pull mine, and because it is forked, it is in danger of going on it's own trail.

**Comment by amneale** [comment] 2018-11-09 09:09
A lot of the classes are actually marked as `final`, meaning you will not be able to extend them even with protected properties, and this is by design: We are trying to keep the objects immutable, i.e. their state should not change after instantiation.

Could you explain your use-case and which classes you are extending in your project?

**Comment by DarkMukke** [comment] 2018-11-11 19:57
```

use Dotmailer\Entity\AddressBook;

class Dotmailer extends \Dotmailer\Dotmailer
{

    /**
     * @param AddressBook $addressBook
     * @return AddressBook
     */
    public function createAddressBook(AddressBook $addressBook): AddressBook
    {
        $this->response = $this->adapter->post('/v2/address-books', $addressBook->asArray());
        $json = json_decode($this->response->getBody()->getContents());
        $addressBook = new AddressBook(
               $json->id,
               $json->name,
               $json->visibility,
               $json->contacts
            );
        return $addressBook;
    }
```
I can't do that with your's as the `$response` and `$adaptor` members are private.
i understand immutable objects, also I often combine method in other methods, and I keep those within the main class as it is where they belong in my opinion.
for example
```
/**
     * @param Contact $contact
     * @return Contact
     */
    public function createAndReturnContact(Contact $contact): Contact
    {
        $this->response = $this->adapter->post('/v2/contacts', $contact->asArray());
        $json = json_decode($this->response->getBody()->getContents());
        $contact = new Contact(
            $json->id,
            $json->email,
            $json->optInType,
            $json->emailType,
            $json->dataFields
        );
        return $contact;
    }
```

**Comment by amneale** [comment] 2018-11-13 12:12
In the first case we would be happy to accept new PRs for any endpoints that are not currently covered!

In the second case if you are doing this in your extending class, you should be able to get the response using the `getResponse` method and build a Contact there

    public function createAndReturnContact(Contact $contact): Contact
    {
        $this->createContact($contact);
        $json = json_decode($this->getResponse()->getBody()->getContents()); 

        return new Contact(
            $json->id,
            $json->email,
            $json->optInType,
            $json->emailType,
            $json->dataFields
        );
    }

You could also do any error handling there

**Closed** 2019-01-04 16:09 UTC
